### ISSUE TITLE
-Wimplicit-fallthrough in drivers/hwmon/tmp401.c

### ISSUE THREAD

**Issue by nathanchance** [ClangBuiltLinux/linux#1505]
```
drivers/hwmon/tmp401.c:526:2: error: unannotated fall-through between switch labels [-Werror,-Wimplicit-fallthrough]
        default:
        ^
drivers/hwmon/tmp401.c:526:2: note: insert 'break;' to avoid fall-through
        default:
        ^
        break;
1 error generated.
```

Patch submitted: https://lore.kernel.org/r/20211116154438.1383290-1-nathan@kernel.org/

**Comment by nathanchance** [comment]
Squashed into the offending commit: https://git.kernel.org/next/linux-next/c/3a15e4cee2be50626b482ff2a9ceae3889034222
