### ISSUE TITLE
-Wframe-larger-than in= in arch/powerpc/kvm/book3s_hv_nested.c

### ISSUE THREAD

**Issue by nathanchance** [ClangBuiltLinux/linux#1292]
```
arch/powerpc/kvm/book3s_hv_nested.c:218:6: error: stack frame size of 2256 bytes in function 'kvmhv_enter_nested_guest' [-Werror,-Wframe-larger-than=]
long kvmhv_enter_nested_guest(struct kvm_vcpu *vcpu)
     ^
1 error generated.
```

This showed up due to enabling the new pass manager by default:

```
$ git bisect log
# bad: [1714ad2336293f351b15dd4b518f9e8618ec38f2] [CSSPGO][llvm-profgen] Aggregate samples on call frame trie to speed up profile generation
# good: [d8e90716dfd186943359c7ade83cc2d1d247f140] [ConstraintElimination] Skip pointer casts.
git bisect start '1714ad2336293f351b15dd4b518f9e8618ec38f2' 'd8e90716dfd186943359c7ade83cc2d1d247f140'
# good: [34eb0adaa9cd76f5bb0549f5a32d6ef452fe977e] [flang] Add -fsyntax-only to f18; retain -fparse-only synonym
git bisect good 34eb0adaa9cd76f5bb0549f5a32d6ef452fe977e
# good: [554cf3729e651b3b5416e081e63670fbe71cf91e] [clang-tblgen] AnnotateAttr::printPretty has spurious comma when no variadic argument is specified
git bisect good 554cf3729e651b3b5416e081e63670fbe71cf91e
# bad: [0a17664b47c153aa26a0d31b4835f26375440ec6] Revert "[LTO] Add option enable NewPM with LTOCodeGenerator."
git bisect bad 0a17664b47c153aa26a0d31b4835f26375440ec6
# good: [d41c6d51cbadbbd0f81c6ac0d6628d01b881e2a5] [libc++] Rationalize our treatment of contiguous iterators and __unwrap_iter().
git bisect good d41c6d51cbadbbd0f81c6ac0d6628d01b881e2a5
# good: [1a13ee1efb62c048c5a38090fe9e64a09df23c03] [GlobalISel] Add sext(constant) -> constant artifact combine.
git bisect good 1a13ee1efb62c048c5a38090fe9e64a09df23c03
# bad: [669ddd1e9b1226432b003dbba05b99f8e992285b] Turn on the new pass manager by default
git bisect bad 669ddd1e9b1226432b003dbba05b99f8e992285b
# good: [b15cbaf5a03d0b32dbc32c37766e32ccf66e6c87] PR49020: Diagnose brace elision in designated initializers in C++.
git bisect good b15cbaf5a03d0b32dbc32c37766e32ccf66e6c87
# first bad commit: [669ddd1e9b1226432b003dbba05b99f8e992285b] Turn on the new pass manager by default
```

Prior to this, it looks like the stack frame of that function was `2016`:

```
arch/powerpc/kvm/book3s_hv_nested.c:218:6: error: stack frame size of 2016 bytes in function 'kvmhv_enter_nested_guest' [-Werror,-Wframe-larger-than=]
long kvmhv_enter_nested_guest(struct kvm_vcpu *vcpu)
     ^
```

**Comment by nickdesaulniers** [comment]
NPM ("new pass manager," as opposed to LPM "legacy pass manager") is a BIG change to LLVM; lots of passes, their orderings, and dependencies change.  This probably won't be the only fallout from it.

**Comment by nathanchance** [comment]
Without NPM:

```
arch/powerpc/kvm/book3s_hv_nested.c:218:6: warning: stack frame size of 2016 bytes in function 'kvmhv_enter_nested_guest' [-Wframe-larger-than=]
long kvmhv_enter_nested_guest(struct kvm_vcpu *vcpu)
     ^
1 warning generated.
```

With NPM:

```
arch/powerpc/kvm/book3s_hv_nested.c:218:6: warning: stack frame size of 2256 bytes in function 'kvmhv_enter_nested_guest' [-Wframe-larger-than=]
long kvmhv_enter_nested_guest(struct kvm_vcpu *vcpu)
     ^
1 warning generated.
```

With NPM + below diff:

```
arch/powerpc/kvm/book3s_hv_nested.c:218:6: warning: stack frame size of 1456 bytes in function 'kvmhv_enter_nested_guest' [-Wframe-larger-than=]
long kvmhv_enter_nested_guest(struct kvm_vcpu *vcpu)
     ^
1 warning generated.
```

```diff
diff --git a/arch/powerpc/kvm/book3s_hv_nested.c b/arch/powerpc/kvm/book3s_hv_nested.c
index 33b58549a9aa..81f3401603de 100644
--- a/arch/powerpc/kvm/book3s_hv_nested.c
+++ b/arch/powerpc/kvm/book3s_hv_nested.c
@@ -51,7 +51,7 @@ void kvmhv_save_hv_regs(struct kvm_vcpu *vcpu, struct hv_guest_state *hr)
        hr->ppr = vcpu->arch.ppr;
 }

-static void byteswap_pt_regs(struct pt_regs *regs)
+static noinline_for_stack void byteswap_pt_regs(struct pt_regs *regs)
 {
        unsigned long *addr = (unsigned long *) regs;

```

Not sure if this is a proper fix but we are running into this in CI now: https://github.com/ClangBuiltLinux/continuous-integration2/runs/1846001679

**Comment by arndb** [comment]
Does it change anything to rewrite the function to use swab64s() instead of swab64()? That should produce slightly better object code in any case.

**Comment by nathanchance** [comment]
Would that just involve changing `*addr = swab64(*addr);` to `swab64s(addr);`? Unless I am missing something, I do not think that buys us anything here. On PowerPC, the expansion is

[`swab64s`](https://elixir.bootlin.com/linux/v5.11-rc7/source/include/linux/swab.h#L20)

to

[`__swab64s`](https://elixir.bootlin.com/linux/v5.11-rc7/source/include/uapi/linux/swab.h#L265)

to

[`*p = __swab64p(p);`](https://elixir.bootlin.com/linux/v5.11-rc7/source/include/uapi/linux/swab.h#L270) because PowerPC does not define `__arch_swab64s`

to

[`*p = __swab64(*p);`](https://elixir.bootlin.com/linux/v5.11-rc7/source/include/uapi/linux/swab.h#L202) because PowerPC does not define `__arch_swab64p`

which matches what the line currently is, since [`swab64` is `__swab64`](https://elixir.bootlin.com/linux/v5.11-rc7/source/include/linux/swab.h#L9).

**Comment by arndb** [comment]
Ah right, I had forgotten that the custom powerpc implementation was replaced with the compiler builtins. I think the 'p' variants were originally introduced for powerpc to make it use the load/store-reverse instructions, but compilers clearly got better since then.

I have reproduced the issue locally now, and I see that powerpc clang fails to optimize the byteswap the way that it is expected to: https://godbolt.org/z/x63a4j
This is likely a problem throughout the kernel, as byteswap is a common operation, and it falls back a naive implementation instead of either the native instruction or one of the known patterns for doing it efficiently through registers.

This is probably a combination of issues, with the kernel failing to use __builtin_bswap64() and the compiler failing to recognize the pattern.

**Comment by arndb** [comment]
I noticed that @nickdesaulniers' 815f0ddb346c ("include/linux/compiler*.h: make compiler-*.h mutually exclusive") seems to have accidentally dropped the __HAVE_BUILTIN_BSWAP64__ that is needed to use the trivial __builtin_bswap64(). I guess that simply putting those back into linux/compiler-clang.h will have a measurable impact on compile speed because this macro is expanded many times. Unfortunately it does not seem to make a difference for the generated code in powerpc64. Maybe clang is able to recognize the pattern as a byteswap but it then fails to find the optimized instruction but uses an architecture-independent fallback itself. See https://godbolt.org/z/3zrcMG for comparing the builtin byteswap with the open-coded one.

**Comment by nathanchance** [comment]
Now that https://git.kernel.org/linus/97e4910232fa1f81e806aa60c25a0450276d99a2 is in mainline, the pseries_defconfig build is now [failing with `clang-12`](https://github.com/ClangBuiltLinux/continuous-integration2/runs/2112645783?check_suite_focus=true), which means that the new pass manager does not appear to be the true culprit (we have had high stack usage in this function without truly realizing it).

Here is where we stand as of 5.12-rc3:

GCC 10.2.0:

```
arch/powerpc/kvm/book3s_hv_nested.c: In function 'kvmhv_enter_nested_guest':
arch/powerpc/kvm/book3s_hv_nested.c:387:1: warning: the frame size of 1280 bytes is larger than 1024 bytes [-Wframe-larger-than=]
  387 | }
      | ^
```

`clang-11` @ [`llvmorg-11-init`](https://github.com/llvm/llvm-project/commit/llvmorg-11-init):

```
arch/powerpc/kvm/book3s_hv_nested.c:264:6: warning: stack frame size of 1712 bytes in function 'kvmhv_enter_nested_guest' [-Wframe-larger-than=]
long kvmhv_enter_nested_guest(struct kvm_vcpu *vcpu)
     ^
1 warning generated.
```

`clang-12` @ [`llvmorg-12-init`](https://github.com/llvm/llvm-project/commit/llvmorg-12-init):

```
arch/powerpc/kvm/book3s_hv_nested.c:264:6: warning: stack frame size of 1712 bytes in function 'kvmhv_enter_nested_guest' [-Wframe-larger-than=]
long kvmhv_enter_nested_guest(struct kvm_vcpu *vcpu)
     ^
1 warning generated.
```

`clang-13` @ [`llvmorg-13-init`](https://github.com/llvm/llvm-project/commit/llvmorg-13-init):

```
arch/powerpc/kvm/book3s_hv_nested.c:264:6: warning: stack frame size of 2480 bytes in function 'kvmhv_enter_nested_guest' [-Wframe-larger-than=]
long kvmhv_enter_nested_guest(struct kvm_vcpu *vcpu)
     ^
1 warning generated.
```

`clang-13` @ https://github.com/llvm/llvm-project/commit/91a6ad5ad887a16e361338303d4ff3d29dba5e10 (NPM):

```
arch/powerpc/kvm/book3s_hv_nested.c:264:6: warning: stack frame size of 2048 bytes in function 'kvmhv_enter_nested_guest' [-Wframe-larger-than=]
long kvmhv_enter_nested_guest(struct kvm_vcpu *vcpu)
     ^
1 warning generated.
```

`clang-13` @ https://github.com/llvm/llvm-project/commit/91a6ad5ad887a16e361338303d4ff3d29dba5e10 (LPM):

```
arch/powerpc/kvm/book3s_hv_nested.c:264:6: warning: stack frame size of 2480 bytes in function 'kvmhv_enter_nested_guest' [-Wframe-larger-than=]
long kvmhv_enter_nested_guest(struct kvm_vcpu *vcpu)
     ^
1 warning generated.
```

There was a massive balloon in stack size between LLVM 12 and 13 and I managed to bisect that to LLVM commit https://github.com/llvm/llvm-project/commit/8ec7ea3ddce7379e13e8dfb4a5260a6d2004aa1c. The stack size increase is visible with or without the new pass manager (the NPM actually makes it not quite as bad).

```
$ git bisect log
# bad: [5369517d20dd362a178a1b2d6c398d8898ee4620] Bump the trunk major version to 13
# good: [7ab7b979d29e1e43701cf690f5cf1903740f50e3] Bump the trunk major version to 12
git bisect start 'llvmorg-13-init' 'llvmorg-12-init'
# good: [7579941d8b02af995e152a453da9b9cc0cc205e7] [examples] Fix Kaleidoscope-Ch3, which was broken by ad92f16ccc5.
git bisect good 7579941d8b02af995e152a453da9b9cc0cc205e7
# bad: [f86ec1e1fc4619d4a3974ab849ad362d6f6906eb] [ScalarizeMaskedMemIntrin] NFC: Convert member functions to static
git bisect bad f86ec1e1fc4619d4a3974ab849ad362d6f6906eb
# good: [885d3f41294665b6d0e523afa94660f929bc1c19] [llvm-mca] Add branch forms of ALU instructions to Cortex-A57 test
git bisect good 885d3f41294665b6d0e523afa94660f929bc1c19
# bad: [389ef79a07850373e2a1f5653d33ce5924bcfe19] [libc++] Add documentation for setting up new CI jobs
git bisect bad 389ef79a07850373e2a1f5653d33ce5924bcfe19
# good: [c80d52e65114060d21b43f22c55bce6b4aa1c9f9] [gn build] (semi-manually) Port 6a8099e0f61
git bisect good c80d52e65114060d21b43f22c55bce6b4aa1c9f9
# bad: [0a1d315f9f166207a95ce5d1e124e1a290807f98] [SLPVectorizer] Fix assert
git bisect bad 0a1d315f9f166207a95ce5d1e124e1a290807f98
# bad: [89df8fc0d73f86cbb2b32a2142a67ec63fd212f0] [AMDGPU][MC] Corrected error position for hwreg() and sendmsg()
git bisect bad 89df8fc0d73f86cbb2b32a2142a67ec63fd212f0
# good: [c044709b8fbea2a9a375e4173a6bd735f6866c0c] [TableGen] Clean up more .td files
git bisect good c044709b8fbea2a9a375e4173a6bd735f6866c0c
# bad: [7fa8b629208c98efa883f7a0e1d51de1d21b104c] [MemorySSA] Add pointer decrement loop clobber test case.
git bisect bad 7fa8b629208c98efa883f7a0e1d51de1d21b104c
# bad: [cf58df29495c2c527e5514bfe8c3582ac774952e] [mlir] Add passes to passes.md to cleanup empty tabs on website index
git bisect bad cf58df29495c2c527e5514bfe8c3582ac774952e
# bad: [237dcfe2e6a29f058f7ada3ba9bfcd6bb55ec76c] Fix build after 54f9ee334
git bisect bad 237dcfe2e6a29f058f7ada3ba9bfcd6bb55ec76c
# bad: [8ec7ea3ddce7379e13e8dfb4a5260a6d2004aa1c] [CostModel] make default size cost for libcalls small (again)
git bisect bad 8ec7ea3ddce7379e13e8dfb4a5260a6d2004aa1c
# good: [8fb73cecfd1a1c0367759721566a91d320f76d8b] [Coroutines] Make sure that async coroutine context size is a multiple of the alignment requirement
git bisect good 8fb73cecfd1a1c0367759721566a91d320f76d8b
# good: [df09f825995b10da03f148133c119f52c94fd6e4] [CostModel] add tests for math library calls; NFC
git bisect good df09f825995b10da03f148133c119f52c94fd6e4
# first bad commit: [8ec7ea3ddce7379e13e8dfb4a5260a6d2004aa1c] [CostModel] make default size cost for libcalls small (again)
```

I tried using cvise to devise something that showed significantly more stack usage with clang-12+ than either GCC or clang-11 and came up with https://godbolt.org/z/754Men.

```c
struct hv_guest_state {
  int vcpu_token;
  long pcr;
  long amor;
  long dpdes;
  long hfscr;
  long tb_offset;
  long srr0;
  long srr1;
  long sprg[4];
  long pidr;
  long cfar;
  long ppr;
  long dawr1;
  long dawrx1;
} kvmhv_write_guest_state_and_regs_l2_hv;
struct pt_regs {
  struct {
    struct {
      long gpr[32];
      long nip;
      long msr;
      long orig_gpr3;
      long ctr;
      long link;
      long xer;
      long ccr;
      long softe;
      long trap;
      long dar;
      long dsisr;
      long result;
    };
    long __pad[4];
  };
} __srcu_read_unlock();
struct kvm_vcpu_arch {
  struct pt_regs regs;
  struct kvmppc_vcore *vcore;
  int trap;
};
struct kvmppc_vcore {
  long tb_offset;
  long pcr;
};
struct kvm_nested_guest {
  long l1_gr_to_hr;
};
int kvm_vcpu_read_guest();
static void kvmhv_update_ptbl_cache(struct kvm_nested_guest *gp) {
  struct kvm_nested_guest __trans_tmp_14 = *gp;
  __srcu_read_unlock(__trans_tmp_14);
}
void byteswap_pt_regs(struct pt_regs *regs) {
  unsigned long *addr = (long *)regs;
  for (; addr < (unsigned long *)(regs + 1); addr++)
    *addr = __builtin_bswap64(*addr);
}
int kvmhv_read_guest_state_and_regs(struct hv_guest_state *l2_hv,
                                    struct pt_regs *l2_regs) {
  return kvm_vcpu_read_guest(l2_hv) || kvm_vcpu_read_guest(l2_regs);
}
long kvmhv_enter_nested_guest(struct kvm_vcpu_arch *vcpu) {
  struct kvm_nested_guest *l2;
  struct pt_regs l2_regs, saved_l1_regs;
  struct hv_guest_state l2_hv;
  struct kvmppc_vcore *vc = vcpu->vcore;
  long regs_ptr = kvmhv_read_guest_state_and_regs(&l2_hv, &l2_regs);
  byteswap_pt_regs(&l2_regs);
  if (!l2->l1_gr_to_hr)
    kvmhv_update_ptbl_cache(l2);
  saved_l1_regs = vcpu->regs;
  vc->tb_offset += l2_hv.tb_offset;
  vcpu->regs = saved_l1_regs;
  vc = vcpu->vcore;
  vc->pcr = 0;
  struct hv_guest_state *hr = 0;
  hr->pidr = hr->dawr1 = __builtin_bswap64(hr->dawr1);
  hr->dawrx1 = __builtin_bswap64(hr->dawrx1);
  byteswap_pt_regs(&l2_regs);
  kvm_vcpu_read_guest(kvmhv_write_guest_state_and_regs_l2_hv, regs_ptr);
  return vcpu->trap;
}
```

At https://github.com/llvm/llvm-project/commit/df09f825995b10da03f148133c119f52c94fd6e4:

```
# LPM
$ clang -O2 --target=powerpc64-linux-gnu -Wno-pointer-sign -Wframe-larger-than=512 -c -o /dev/null book3s_hv_nested.i
book3s_hv_nested.i:63:6: warning: stack frame size of 1136 bytes in function 'kvmhv_enter_nested_guest' [-Wframe-larger-than=]
long kvmhv_enter_nested_guest(struct kvm_vcpu_arch *vcpu) {
     ^
1 warning generated.

# NPM
$ clang -fexperimental-new-pass-manager -O2 --target=powerpc64-linux-gnu -Wno-pointer-sign -Wframe-larger-than=512 -c -o /dev/null book3s_hv_nested.i
book3s_hv_nested.i:63:6: warning: stack frame size of 640 bytes in function 'kvmhv_enter_nested_guest' [-Wframe-larger-than=]
long kvmhv_enter_nested_guest(struct kvm_vcpu_arch *vcpu) {
     ^
1 warning generated.
```

At https://github.com/llvm/llvm-project/commit/8ec7ea3ddce7379e13e8dfb4a5260a6d2004aa1c:

```
# LPM
$ clang -O2 --target=powerpc64-linux-gnu -Wno-pointer-sign -Wframe-larger-than=512 -c -o /dev/null book3s_hv_nested.i
book3s_hv_nested.i:54:6: warning: stack frame size of 944 bytes in function 'byteswap_pt_regs' [-Wframe-larger-than=]
void byteswap_pt_regs(struct pt_regs *regs) {
     ^
book3s_hv_nested.i:63:6: warning: stack frame size of 2064 bytes in function 'kvmhv_enter_nested_guest' [-Wframe-larger-than=]
long kvmhv_enter_nested_guest(struct kvm_vcpu_arch *vcpu) {
     ^
2 warnings generated.

# NPM
$ clang -fexperimental-new-pass-manager -O2 --target=powerpc64-linux-gnu -Wno-pointer-sign -Wframe-larger-than=512 -c -o /dev/null book3s_hv_nested.i
book3s_hv_nested.i:54:6: warning: stack frame size of 944 bytes in function 'byteswap_pt_regs' [-Wframe-larger-than=]
void byteswap_pt_regs(struct pt_regs *regs) {
     ^
book3s_hv_nested.i:63:6: warning: stack frame size of 1520 bytes in function 'kvmhv_enter_nested_guest' [-Wframe-larger-than=]
long kvmhv_enter_nested_guest(struct kvm_vcpu_arch *vcpu) {
     ^
2 warnings generated.
```

**Comment by arndb** [comment]
How hard would it be to implement __builtin_bswap64() using the native instruction on ppc64?
I think that would solve this problem as well as improve performance of the kernel on ppc64 in general.

**Comment by nathanchance** [comment]
I am not sure. I have gone ahead and reported this upstream: https://llvm.org/pr49610

**Comment by nathanchance** [comment]
Workaround submitted: https://lore.kernel.org/r/20210621182440.990242-1-nathan@kernel.org/

**Comment by nathanchance** [comment]
Workaround accepted: https://git.kernel.org/powerpc/c/51696f39cbee5bb684e7959c0c98b5f54548aa34

**Comment by nickdesaulniers** [comment]
@nemanjai also has https://reviews.llvm.org/D104836 which @nathanchance confirmed helps.

**Comment by nathanchance** [comment]
https://git.kernel.org/torvalds/c/51696f39cbee

https://github.com/llvm/llvm-project/commit/0464586ac515e8cfebe4c7615387fd625c8869f5
