### ISSUE TITLE
-Wmacro-redefined in include/linux/fortify-string.h

### ISSUE THREAD

**Issue by nathanchance** [ClangBuiltLinux/linux#1741]
When building `x86_64_defconfig` on mainline with `CONFIG_KMSAN=y` and `CONFIG_FORTIFY_SOURCE=y`, I see the following warning/error:

```
In file included from scripts/mod/devicetable-offsets.c:3:
In file included from ./include/linux/mod_devicetable.h:13:
In file included from ./include/linux/uuid.h:12:
In file included from ./include/linux/string.h:253:
./include/linux/fortify-string.h:496:9: error: 'memcpy' macro redefined [-Werror,-Wmacro-redefined]
#define memcpy(p, q, s)  __fortify_memcpy_chk(p, q, s,                  \
        ^
./arch/x86/include/asm/string_64.h:17:9: note: previous definition is here
#define memcpy __msan_memcpy
        ^
In file included from scripts/mod/devicetable-offsets.c:3:
In file included from ./include/linux/mod_devicetable.h:13:
In file included from ./include/linux/uuid.h:12:
In file included from ./include/linux/string.h:253:
./include/linux/fortify-string.h:500:9: error: 'memmove' macro redefined [-Werror,-Wmacro-redefined]
#define memmove(p, q, s)  __fortify_memcpy_chk(p, q, s,                 \
        ^
./arch/x86/include/asm/string_64.h:73:9: note: previous definition is here
#define memmove __msan_memmove
        ^
2 errors generated.
```

This appears to be caused by commit [ff901d80fff6](https://git.kernel.org/linus/ff901d80fff6d65ada6f2a60a1f7d180ee2e0416) ("x86: kmsan: use __msan_ string functions where possible."). That change did include a fix for this issue with `memset()` but not `memcpy()` or `memmove()`. If I apply a similar change:

```diff
diff --git a/include/linux/fortify-string.h b/include/linux/fortify-string.h
index 4029fe368a4f..718ee17b31e3 100644
--- a/include/linux/fortify-string.h
+++ b/include/linux/fortify-string.h
@@ -493,6 +493,7 @@ __FORTIFY_INLINE bool fortify_memcpy_chk(__kernel_size_t size,
  * __struct_size() vs __member_size() must be captured here to avoid
  * evaluating argument side-effects further into the macro layers.
  */
+#ifndef CONFIG_KMSAN
 #define memcpy(p, q, s)  __fortify_memcpy_chk(p, q, s,                 \
                __struct_size(p), __struct_size(q),                     \
                __member_size(p), __member_size(q),                     \
@@ -501,6 +502,7 @@ __FORTIFY_INLINE bool fortify_memcpy_chk(__kernel_size_t size,
                __struct_size(p), __struct_size(q),                     \
                __member_size(p), __member_size(q),                     \
                memmove)
+#endif

 extern void *__real_memscan(void *, int, __kernel_size_t) __RENAME(memscan);
 __FORTIFY_INLINE void *memscan(void * const POS0 p, int c, __kernel_size_t size)
```

The warnings disappear but there are new ones because the fortify tests do not pass anymore:

```
warning: unsafe memcpy() usage lacked '__read_overflow2' symbol in lib/test_fortify/read_overflow2-memcpy.c
warning: unsafe memmove() usage lacked '__read_overflow2' symbol in lib/test_fortify/read_overflow2-memmove.c
warning: unsafe memcpy() usage lacked '__read_overflow2_field' symbol in lib/test_fortify/read_overflow2_field-memcpy.c
warning: unsafe memmove() usage lacked '__read_overflow2_field' symbol in lib/test_fortify/read_overflow2_field-memmove.c
warning: unsafe memcpy() usage lacked '__write_overflow' symbol in lib/test_fortify/write_overflow-memcpy.c
warning: unsafe memmove() usage lacked '__write_overflow' symbol in lib/test_fortify/write_overflow-memmove.c
warning: unsafe memset() usage lacked '__write_overflow' symbol in lib/test_fortify/write_overflow-memset.c
warning: unsafe memcpy() usage lacked '__write_overflow_field' symbol in lib/test_fortify/write_overflow_field-memcpy.c
warning: unsafe memmove() usage lacked '__write_overflow_field' symbol in lib/test_fortify/write_overflow_field-memmove.c
warning: unsafe memset() usage lacked '__write_overflow_field' symbol in lib/test_fortify/write_overflow_field-memset.c
```

I have started a thread upstream around this: https://lore.kernel.org/Y1AZr01X1wvg5Klu@dev-arch.thelio-3990X/

**Comment by nickdesaulniers** [comment]
https://github.com/google/kmsan/issues/89

**Comment by nathanchance** [comment]
https://lore.kernel.org/20221024212144.2852069-5-glider@google.com/

**Comment by nathanchance** [comment]
https://git.kernel.org/akpm/mm/c/78a498c3a227f2ac773a8234b2ce092a4403f2c3

**Comment by nathanchance** [comment]
https://git.kernel.org/linus/78a498c3a227f2ac773a8234b2ce092a4403f2c3
