### ISSUE TITLE
-Wmissing-braces in net/bpf/test_run.c

### ISSUE THREAD

**Issue by nathanchance** [ClangBuiltLinux/linux#230]
```
net/bpf/test_run.c:120:20: error: suggest braces around initialization of subobject [-Werror,-Wmissing-braces]
        struct sock sk = {0};
                          ^
                          {}
```

Patch sent: https://lore.kernel.org/lkml/20181019182649.24301-1-natechancellor@gmail.com/

**Comment by nathanchance** [comment]
Patch rejected as the offending commit is no longer in the bpf-next tree:
