### ISSUE TITLE
Invalid absolute R_X86_64_64 relocation: L3_START_KERNEL

### ISSUE THREAD

**Issue by nathanchance** [ClangBuiltLinux/linux#984]
When building [my WSL2 kernel](https://github.com/nathanchance/WSL2-Linux-Kernel) with `LLVM_IAS=1`, I get the following error when building the compressed kernel:

```
Invalid absolute R_X86_64_64 relocation: L3_START_KERNEL
```

If you want to reproduce:

```
$ git clone https://github.com/nathanchance/WSL2-Linux-Kernel

$ cd WSL2-Linux-Kernel

$ ./build.sh LLVM_IAS=1
```

This might be related to LTO but I cannot fully tell given that when `CONFIG_LTO_CLANG` is disabled and I have applied a fix to build without `ld` period, I cannot finish building:

```
Cannot find symbol for section 2: .text.
init/initramfs.o: failed
```

```diff
diff --git a/Makefile b/Makefile
index 847cc432adbf..ebbc76452f46 100644
--- a/Makefile
+++ b/Makefile
@@ -1048,7 +1048,7 @@ HOST_LIBELF_LIBS = $(shell pkg-config libelf --libs 2>/dev/null || echo -lelf)

 ifdef CONFIG_STACK_VALIDATION
   has_libelf := $(call try-run,\
-               echo "int main() {}" | $(HOSTCC) -xc -o /dev/null $(HOST_LIBELF_LIBS) -,1,0)
+               echo "int main() {}" | $(HOSTCC) -xc -o /dev/null $(HOSTLDFLAGS) $(HOST_LIBELF_LIBS) -,1,0)
   ifeq ($(has_libelf),1)
     objtool_target := tools/objtool FORCE
   else
```

**Comment by nathanchance** [comment]
So couple of updates:

1. `Invalid absolute R_X86_64_64 relocation: L3_START_KERNEL` appears after commit [542612e0e016](https://git.kernel.org/pub/scm/linux/kernel/git/next/linux-next.git/commit/?id=542612e0e016677dada15a8da9557e918cd0a5bb) ("seq_read-info-message-about-buggy-next-functions-fix") in -next. No idea why but that is what `git bisect` told me...

2. The second error `Cannot find symbol for section 2: .text.` happens when `CONFIG_FUNCTION_TRACER` is enabled because this comes from `scripts/recordmcount.h`. I've split this off into a second issue: https://github.com/ClangBuiltLinux/linux/issues/986

**Comment by nathanchance** [comment]
More consistent reproducer that does not involve the state of my tree:

```
$ git clone git://git.kernel.org/pub/scm/linux/kernel/git/next/linux-next.git

$ cd linux-next

$ curl -LSs https://gist.github.com/nathanchance/e59b045fd55ec67947208a0faff8473f/raw/d7e2de4f2c8815d9fde7d133e15ed8075372434d/gistfile1.txt | git apply -3v

$ curl -LSso arch/x86/configs/x86_64_defconfig https://raw.githubusercontent.com/nathanchance/WSL2-Linux-Kernel/e34017aa13b0ed0ccf01339e4c2589c3a80c1e16/arch/x86/configs/wsl2_defconfig

$ make -j$(nproc) -s LLVM=1 LLVM_IAS=1 O=out/x86_64 distclean defconfig bzImage
```

**Comment by nathanchance** [comment]
I have never seen this again.
