### ISSUE TITLE
"error: expected string literal in 'asm'" in include/asm-generic/rwonce.h

### ISSUE THREAD

**Issue by nathanchance** [ClangBuiltLinux/linux#1728]
When building an arm64 kernel with `CONFIG_LTO` after commit [ba00c2a04fa5](https://git.kernel.org/arm64/c/ba00c2a04fa5431d204a4183062b30372c062aa7) ("arm64: fix the build with binutils 2.27"), I see errors along the following lines:

```
In file included from arch/arm64/kernel/module-plts.c:6:
In file included from include/linux/elf.h:6:
In file included from arch/arm64/include/asm/elf.h:8:
In file included from arch/arm64/include/asm/hwcap.h:9:
In file included from arch/arm64/include/asm/cpufeature.h:9:
In file included from arch/arm64/include/asm/alternative-macros.h:5:
In file included from include/linux/bits.h:22:
In file included from include/linux/build_bug.h:5:
In file included from include/linux/compiler.h:248:
In file included from arch/arm64/include/asm/rwonce.h:71:
include/asm-generic/rwonce.h:67:9: error: expected string literal in 'asm'
        return __READ_ONCE(*(unsigned long *)addr);
              ^
arch/arm64/include/asm/rwonce.h:43:16: note: expanded from macro '__READ_ONCE'
                asm volatile(__LOAD_RCPC(b, %w0, %1)                    \
                            ^
arch/arm64/include/asm/rwonce.h:17:2: note: expanded from macro '__LOAD_RCPC'
        ALTERNATIVE(                                                    \
        ^
```

Patch submitted: https://lore.kernel.org/20221003193759.1141709-1-nathan@kernel.org/

**Comment by nickdesaulniers** [comment]
Accepted: https://git.kernel.org/pub/scm/linux/kernel/git/arm64/linux.git/commit/?id=d2995249a2f7

Not yet in -next as of 20221005, maybe tomorrow.

**Comment by nathanchance** [comment]
https://git.kernel.org/linus/d2995249a2f72333a4ab4922ff3c42a76c023791
